const config = require('../config');
const { levelConstant } = require('../constants/levelConstant');

const integrationConstant = {
  // SQL queries constants
  CHECK_VETERAN_ALREADY_EXISTS:
    'SELECT id from college_external_service WHERE uuid = ? AND parent_college_id = ? AND source = ?',
  MAPPED_DEGREE_WITHOUT_REFERENCE:
    'SELECT program_name as degreename FROM cr_bucket_degree_list as crl LEFT JOIN college_degree_mapping as mm ON crl.id=mm.bucket_degree_id WHERE crl.bucket_id IN (?) and crl.secondary_bucket_id IN (?) and mm.level_type IN (?) and mm.college_id = ?',
  MAPPED_DEGREE_WITH_REFERENCE:
    'SELECT reference_code as degreename FROM cr_bucket_degree_list as crl LEFT JOIN college_degree_mapping as mm ON crl.id=mm.bucket_degree_id WHERE crl.bucket_id IN (?) and crl.secondary_bucket_id IN (?) and mm.level_type IN (?) and mm.college_id=?',
  INSERT_INTO_LOG_ENTRY: 'INSERT INTO log_entry SET ?',
  INSERT_THIRD_PARTY_RESPONSE: 'INSERT INTO college_external_service SET ?',
  SEPCIFIC_DEGREE_BUCKET_DATA:
    'SELECT level_id as level, bucket_id as primaryBucket, sec_bucket_id as secondaryBucket FROM college_degree_specific_info WHERE college_info_id = ?',
  DEGREE_NAMES:
    'SELECT pb.title as primaryBucket, sb.title as secondaryBucket FROM bucket_degree pb LEFT JOIN  bucket_secondary_degree sb ON pb.id = sb.bucket_degree_id WHERE pb.id = ? AND sb.id = ?',

  // Log entry constants
  BEFORE_INTEGRATION: 'Before sending API POST request.',
  AFTER_INTEGRATION: 'After sending API POST request.',
  BEFORE_INSERT_GOOGLESHEET: 'Before posting to google sheets.',
  AFTER_INSERT_GOOGLESHEET: 'After posting to google sheets.',
  INTEGRATION_STAGE: 'Third party integration',
  GOOGLE_SHEET_STAGE: 'Google sheet service',
  SFTP_STAGE: 'SFTP',
  RECON_STAGE: 'Recon message',
  VETERAN_EMAIL: 'Veteran email',
  STATUS_SUCCESS: 'Success',
  STATUS_FAILURE: 'Failure',

  // Common message constants
  DUPLICATE_MESSAGE: 'User already requested from this college.',
  NO_PHONE_ZIP_MESSAGE:
    'Phone number and zip code are empty or in wrong format',
  NO_ZIP_MESSAGE: 'Zip code empty or in worng format',
  NO_PHONE_MESSAGE: 'Phone number empty or in wrong format',
  NO_DEGREE_MESSAGE: 'No matching program name',
  NO_LEVEL_MESSAGE: 'No matching degree level',
  VETERAN_REQUEST_MESSAGE: 'Veteran has not registerd to the school',
  REQUIRED_PARAMETER_PASS: 'Required parameters passed',
  DEGREE_LABEL_MATCH: 'Degree Level matched',
  DEGREE_LABEL_NOT_MATCH: 'Degree level did not match.',
  PROGRAM_NOT_MATCH: 'Program name did not match.',
  PROGRAM_MATCH: 'Program matched.',

  // other constants
  IP_ADDRESS: config.IP_ADDRESS,

  // POST URL
  BISK_POST_URL:
    'https://bisk.my.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8',
  WILEY_POST_URL: 'https://leadiq.sparkroom.com/Sparkroom/postLead',

  BAYSTATE_POST_URL:
    'https://connect.baystate.edu/manage/service/import?cmd=load&format=d247661e-3182-44cd-8f26-388d8362bc3a',
  TIFFIN_POST_URL:
    'https://apply.tiffin.edu/manage/service/import?cmd=load&format=f1463030-81df-4b5a-9ffe-c73f5cf369a1',
  CINCINNATI_POST_URL:
    'https://uc-online.my.salesforce-sites.com/services/data/v50.0/sobjects/Interaction__c',
  //CONCORDE_POST_URL: "https://webservices3.concorde.edu/webservices/submitCurl2/httpPost",
  CONCORDE_POST_URL:
    'https://webservices3.concorde.edu/webservices/SubmitCurl2/rawInquiry/6',
  CSU_POST_URL: 'https://input.data-hq.com/',
  CAREERSTEP_POST_URL: 'https://leads.careerstep.com/leadpost.php',
  COLORADO_STATE_POST_URL: 'https://leads.theusim.com/datain.ashx',
  GOLDENGATE_POST_URL: 'https://www.ggu.edu/GGURFI',
  POST_UNIVERSITY_URL: 'http://partners.educationdynamics.com/api/lead/save',
  NOODLE_POST_URL: 'https://api.noodle.com/api/v1/inquiries',

  INTEGRATION_TYPE: Object.freeze({
    INDIVIDUAL: 'individual',
    WILEY: 'wiley',
    BISK: 'bisk',
    SFTP: 'sftp',
    EVERSPRING: 'everspring',
    NOODLE: 'noodle',
    SPARKROOM: 'sparkroom',
  }),
};

const collegeConstant = {
  // WILEY
  // NORWICH: {
  //   collegeId: 3110,
  //   collegeName: "Norwich Univeristy",
  //   levels: [levelConstant.BACHELOR, levelConstant.MASTER],
  //   additionalParameters: {
  //     LeadBuyerID: "Wiley-NorwichUniversity",
  //     campusID: "default",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // UTICA: {
  //   collegeId: 2145,
  //   collegeName: "Utica College",
  //   levels: [
  //     levelConstant.BACHELOR,
  //     levelConstant.MASTER,
  //     levelConstant.DOCTORATE,
  //     levelConstant.CERTIFICATE,
  //   ],
  //   additionalParameters: {
  //     LeadBuyerID: "UticaCollege2",
  //     campusID: "Online",
  //     RNLicense: "Yes",
  //     PHYSTHER: "Yes",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // WEST_FLORIDA: {
  //   collegeId: 650,
  //   collegeName: "University of West Florida",
  //   levels: [levelConstant.BACHELOR, levelConstant.MASTER],
  //   additionalParameters: {
  //     LeadBuyerID: "UniversityofWestFlorida",
  //     campusID: "Online",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // KENTUCKY: {
  //   collegeId: 1148,
  //   collegeName: "University of Kentucky",
  //   levels: [levelConstant.MASTER],
  //   additionalParameters: {
  //     LeadBuyerID: "Wiley-UK",
  //     campusID: "Online",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // LOTL_UNIVERSITY: {
  //   collegeId: 2992,
  //   collegeName: "Lady of the Lake Univeristy",
  //   levels: [levelConstant.BACHELOR, levelConstant.MASTER],
  //   additionalParameters: {
  //     LeadBuyerID: "LadyoftheLakeUniv",
  //     campusID: "Online",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // MSU: {
  //   collegeId: 1440,
  //   collegeName: "Michigan State University",
  //   levels: [
  //     levelConstant.POST_BACHELOR,
  //     levelConstant.MASTER,
  //     levelConstant.CERTIFICATE,
  //   ],
  //   additionalParameters: {
  //     bisk: {
  //       Campaign_ID: "7014M000001sSJUQA2",
  //       lead_source: "Internet",
  //       oid: "00D61000000Ju34",
  //       retURL: "",
  //       "00N6100000DVxWP": "",
  //       country_code: "US",
  //       "00N6100000DVxVv": "",
  //       "00N6100000DVxWm": "Dependent",
  //       "00N6100000DVxVu": "",
  //       "00N6100000DVxXY": "",
  //       "00N6100000DVxXh": "",
  //       "00N6100000I9aFq": "Granted",
  //       "Salesforce University ID": "0016100000TWYsWAAX",
  //       "00N6100000DVxXc": "",
  //       "00N6100000DVxXe": "",
  //     },

  //     wiley: {
  //       LeadBuyerID: "MSU",
  //       campusID: "Online",
  //     },
  //   },
  //   type: ["wiley", "bisk"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // GEORGETOWN_MSB: {
  //   collegeId: 3623,
  //   collegeName: "Georgetown University MSB",
  //   levels: [levelConstant.MASTER],
  //   additionalParameters: {
  //     LeadBuyerID: "Wiley-GeorgetownUniversityMSB",
  //     campusID: "Online",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // GEORGETOWN: {
  //   collegeId: 557,
  //   collegeName: "Georgetown University",
  //   levels: [levelConstant.MASTER],
  //   additionalParameters: {
  //     LeadBuyerID: "GeorgetownUniversity",
  //     campusID: "Online",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // GEORGEMASON: {
  //   collegeId: 3088,
  //   collegeName: "Georgemason University",
  //   levels: [
  //     levelConstant.POST_BACHELOR,
  //     levelConstant.MASTER,
  //     levelConstant.CERTIFICATE,
  //   ],
  //   additionalParameters: {
  //     LeadBuyerID: "GeorgeMasonUniversity",
  //     campusID: "Online",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // EASTERN_OREGON: {
  //   collegeId: 2444,
  //   collegeName: "Eastern Oregon Univeristy",
  //   levels: [
  //     levelConstant.BACHELOR,
  //     levelConstant.POST_BACHELOR,
  //     levelConstant.MASTER,
  //   ],
  //   additionalParameters: {
  //     LeadBuyerID: "EasternOregon",
  //     campusID: "Default",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // EAST_CENTRAL: {
  //   collegeId: 2384,
  //   collegeName: "East Central University",
  //   levels: [
  //     levelConstant.BACHELOR,
  //     levelConstant.MASTER,
  //     levelConstant.CERTIFICATE,
  //   ],
  //   additionalParameters: {
  //     LeadBuyerID: "EastCentralUniversity",
  //     campusID: "Default",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },
  // AMERICAN: {
  //   collegeId: 553,
  //   collegeName: "American University",
  //   levels: [levelConstant.POST_BACHELOR, levelConstant.MASTER],
  //   additionalParameters: {
  //     LeadBuyerID: "AmericanUniversity",
  //     campusID: "Online",
  //     MECON1: "Yes",
  //     MECON2: "Yes",
  //     MSTRATCOM: "Yes",
  //     MPAP: "Yes",
  //   },
  //   type: ["wiley"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: ["phone", "zip"],
  //   googleSheetID: [],
  //   singleDegree: null,
  // },

  // other third party integration
  COLORADO_STATE: {
    status: false,
    collegeId: 3395,
    collegeName: 'Colorado State University-Global',
    levels: [levelConstant.BACHELOR, levelConstant.MASTER],
    additionalParameters: {
      acknowledge: 1,
      pub_id: 10712,
    },
    type: ['other'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: ['phone'],
    googleSheetID: [],
    singleDegree: null,
  },

  SNHU: {
    collegeId: 3755,
    collegeName: 'Southern New Hampshire University - Online',
    levels: [
      levelConstant.ASSOCIATE,
      levelConstant.BACHELOR,
      levelConstant.MASTER,
    ],
    additionalParameters: {
      LeadBuyerID: 'SNHU',
      Source: 'collegerecon-military',
    },
    type: ['other'],
    hasReferanceCode: true,
    defaultDegree: 'UG.HLP',
    requiredParameters: ['phone', 'zip'],
    googleSheetID: ['1T9bsDZws-QJPiqWUIOaTJC-224EpBbiYtM_JvXo7lu4'],
    singleDegree: null,
  },

  CAREERSTEP: {
    status: false,
    collegeId: 3708,
    collegeName: 'CareerStep',
    levels: [levelConstant.CERTIFICATE],
    additionalParameters: {
      LeadGroup: 'Military',
      SourceID: 'aff|collegerecon',
      AlternateID: 'aff|collegerecon',
      Login: 'collegerecon',
      PW: 'CRECON8',
    },
    type: ['other'],
    hasReferanceCode: true,
    defaultDegree: '',
    requiredParameters: ['phone'],
    googleSheetID: [],
    singleDegree: null,
  },

  CSU: {
    status: false,
    collegeId: 3775,
    collegeName: 'Columbia Southern University',
    levels: [
      levelConstant.ASSOCIATE,
      levelConstant.BACHELOR,
      levelConstant.MASTER,
      levelConstant.DOCTORATE,
    ],
    additionalParameters: {
      LeadBuyerID: 'CSU',
      VendorID: 'COLRECON',
    },
    type: ['other'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: ['phone'],
    googleSheetID: [],
    singleDegree: null,
  },

  CONCORDE: {
    collegeId: 3774,
    collegeName: 'Concorde Career College',
    levels: [
      levelConstant.ASSOCIATE,
      levelConstant.BACHELOR,
      levelConstant.CERTIFICATE,
    ],
    additionalParameters: {
      LocationID: 'online',
      SourceID: 'CLLGRC',
    },
    type: ['other'],
    hasReferanceCode: false,
    defaultDegree: 'Undecided',
    requiredParameters: ['phone'],
    googleSheetID: [],
    singleDegree: 'Undecided',
  },

  CINCINNATI: {
    collegeId: 2312,
    collegeName: 'University Of Cincinnati Online',
    levels: [
      levelConstant.ASSOCIATE,
      levelConstant.BACHELOR,
      levelConstant.CERTIFICATE,
      levelConstant.MASTER,
      levelConstant.POST_BACHELOR,
      levelConstant.POST_MASTER,
      levelConstant.DOCTORATE,
    ],
    additionalParameters: {
      accessTokenData: {
        client_id: config.CINCINNATI_CLIENT_ID,
        client_secret: config.CINCINNATI_CLIENT_SECRET,
        refresh_token: config.CINCINNATI_REFRESH_TOKEN,
        grant_type: 'refresh_token',
      },

      requestBodyConstant: {
        Interaction_Source__c: 'College Recon',
        // Military_Affiliation__c: "Not Affiliated",
        Mailing_Country__c: 'United States',
        Marketing_Campaign__c: 'MIL_VET_CollegeRecon_General',
        Medium__c: 'OED',
        Source__c: 'Home Front Alliance',
        Channel__c: 'Other Paid',
      },
    },
    type: ['other'],
    hasReferanceCode: true,
    defaultDegree: 'a114T00000153u7',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  TIFFIN: {
    status: false,
    collegeId: 2303,
    collegeName: 'Tiffin University',
    levels: [
      levelConstant.DOCTORATE,
      levelConstant.BACHELOR,
      levelConstant.CERTIFICATE,
      levelConstant.MASTER,
      levelConstant.POST_BACHELOR,
      levelConstant.POST_MASTER,
    ],
    additionalParameters: {
      authenticationParameters: {
        username: config.TIFFIN_USERNAME,
        password: config.TIFFIN_PASSWORD,
      },
    },
    type: ['other'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  FORT_HAYS: {
    status: false,
    collegeId: 1074,
    collegeName: 'Fort Hays State University: Online',
    levels: [
      levelConstant.ASSOCIATE,
      levelConstant.BACHELOR,
      levelConstant.MASTER,
    ],
    additionalParameters: {
      apiKey: config.FORT_HAYS_API_KEY,
    },
    type: ['other'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  BAY_STATE: {
    status: false,
    collegeId: 3704,
    collegeName: 'Bay State College',
    levels: [...Object.values(levelConstant)],
    additionalParameters: {
      basicAuth: {
        username: config.BAY_STATE_USERNAME,
        password: config.BAY_STATE_PASSWORD,
      },
    },
    type: ['other'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  POST: {
    status: false,
    collegeId: 3451,
    collegeName: 'Post University - Online',
    levels: [3, 5, 7],
    additionalParameters: {
      APIKey: config.POST_API_KEY,
      SourceCode: 'COL-RCN',
    },
    type: ['other'],
    hasReferanceCode: true,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  GOLDENGATE: {
    collegeId: 211,
    collegeName: "Golden Gate University San Francisco",
    levels: [...Object.values(levelConstant)],
    additionalParameters: {
      basicAuth: {
        username: config.GOLDENGATE_USERNAME,
        password: config.GOLDENGATE_PASSWORD,
      },

      constantParameters: {
        ggu_channel: "C-Web",
        ggu_source: "Web RFI",
        ggu_utm_source: "rfi",
        ggu_utm_medium: "organic",
        ggu_utm_clientId: "VirtualVC",
        ggu_utm_campaign: "CollegeRecon",
        ggu_utm_term: "",
        ggu_utm_context: "",
        inquiry_source: "ggurfi",
        veteranflag: "yes",
        entryterm: "21/FA",
        preferredphone: "Mobile Phone",
      },
    },
    type: ["other"],
    hasReferanceCode: false,
    defaultDegree: {
      areaOfInterest: "GS.UD",
      academicProgram: "OPEN.DUG",
      programType: "DS-UG",
    },
    requiredParameters: [],
    googleSheetID: [],
  },

  // BISK
  // FLORIDA_TECH: {
  //   collegeId: 600,
  //   collegeName: "Florida Tech",
  //   levels: [
  //     levelConstant.ASSOCIATE,
  //     levelConstant.BACHELOR,
  //     levelConstant.MASTER,
  //   ],
  //   additionalParameters: {
  //     Campaign_ID: "7014M000001sSJKQA2",
  //     lead_source: "Internet",
  //     List: 1979,
  //     oid: "00D61000000Ju34",
  //     retURL: "",
  //     "00N6100000DVxWP": "",
  //     country_code: "US",
  //     "00N6100000DVxVv": "",
  //     "00N6100000DVxVi": "",
  //     "00N6100000DVxVD": "",
  //     "00N6100000DVxXY": "",
  //     "00N6100000DVxXh": "",
  //     "00N6100000I9aFq": "Granted",
  //     "Salesforce University ID": "0016100000TWYsZAAX",
  //     "00N6100000DVxXc": "",
  //     "00N6100000DVxXe": "",
  //   },
  //   type: ["bisk"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: [],
  //   googleSheetID: [],
  // },

  // NOTRE_DOME: {
  //   collegeId: 1030,
  //   collegeName: "University Of Notre Dame",
  //   levels: [levelConstant.POST_BACHELOR, levelConstant.CERTIFICATE],
  //   additionalParameters: {
  //     Campaign_ID: "7014M000001sSJZQA2",
  //     lead_source: "Internet",
  //     oid: "00D61000000Ju34",
  //     retURL: "",
  //     "00N6100000DVxWP": "",
  //     ThankYouUrl: "",
  //     country_code: "US",
  //     "00N6100000DVxVu": "",
  //     "00N6100000DVxVv": "",
  //     "00N6100000DVxWm": "Dependent",
  //     "00N6100000DVxVi": "",
  //     "00N6100000DVxXh": "",
  //     "00N6100000I9aFq": "Granted",
  //     "Salesforce University ID": "0016100000TWYsVAAX",
  //     "00N6100000DVxXc": "",
  //     "00N6100000DVxXe": "",
  //   },
  //   type: ["bisk"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: [],
  //   googleSheetID: [],
  // },

  // VILLANOVA: {
  //   collegeId: 2540,
  //   collegeName: "Villanova University",
  //   levels: [levelConstant.MASTER, levelConstant.CERTIFICATE],
  //   additionalParameters: {
  //     Campaign_ID: "7014M000001sSJPQA2",
  //     lead_source: "Internet",
  //     oid: "00D61000000Ju34",
  //     retURL: "",
  //     "00N6100000DVxWP": "",
  //     country_code: "US",
  //     "00N6100000DVxVv": "",
  //     "00N6100000DVxWm": "Dependent",
  //     "00N6100000DVxXY": "",
  //     "00N6100000DVxVD": "",
  //     "00N6100000DVxVi": "",
  //     "00N6100000DVxXh": "",
  //     "00N6100000I9aFq": "Granted",
  //     "Salesforce University ID": "0016100000TWYsXAAX",
  //     "00N6100000DVxXc": "",
  //     "00N6100000DVxXe": "",
  //     "00N6100000DVxXf": config.IP_ADDRESS,
  //   },
  //   type: ["bisk"],
  //   hasReferanceCode: true,
  //   defaultDegree: "",
  //   requiredParameters: [],
  //   googleSheetID: [],
  // },

  // SFTP

  FAYATTEVILLE: {
    status: false,
    collegeId: 1845,
    collegeName: 'Fayetteville State University',
    levels: [],
    additionalParameters: {
      host: 'sftp.admissionpros.com',
      port: '22',
      username: 'fsuuser',
    },
    type: ['sftp'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  KENT_STATE: {
    collegeId: 2351,
    collegeName: 'Kent State University',
    levels: [],
    additionalParameters: {
      host: 'ft.technolutions.net',
      port: '22',
      username: 'college_recon_leads@apply.kent.edu',
    },
    type: ['sftp'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  PNW: {
    collegeId: 1037,
    collegeName: 'Purdue University Northwest-Hammond',
    levels: [],
    additionalParameters: {
      host: 'ft.technolutions.net',
      port: 22,
      username: 'collegerecon@discover.pnw.edu',
    },
    type: ['sftp'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  EMBRYRIDDLE: {
    status: true,
    collegeId: 3836,
    collegeName: 'Embry-Riddle Aeronautical University-Worldwide',
    levels: [],
    additionalParameters: {
      host: config.COLLEGERECON_HOST,
      port: 22,
      username: config.EMBRYRIDDLE_USERNAME,
      password: config.EMBRYRIDDLE_PASSWORD,
    },
    type: ['sftp'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  ARKANSAS_STATE: {
    status: true,
    collegeId: 86,
    collegeName: 'Arkansas State University-Main Campus',
    levels: [],
    additionalParameters: {
      host: config.COLLEGERECON_HOST,
      port: 22,
      username: config.ARKANSAS_STATE_USERNAME,
      password: config.ARKANSAS_STATE_PASSWORD,
    },
    type: ['sftp'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },

  //EverSpring
  WILLIAM_AND_MARY_MBA: {
    collegeId: 3933,
    collegeName: 'William and Marry, Mason Master Business Administration',
    levels: [levelConstant.MASTER],
    additionalParameters: {},
    type: ['everspring'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
  WILLIAM_AND_MARY_MSBA: {
    collegeId: 3932,
    collegeName: 'William and Marry, Mason Master Science Business Analytics',
    levels: [levelConstant.MASTER],
    additionalParameters: {},
    type: ['everspring'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
  KENT_STATE_MS_HEALTH: {
    collegeId: 3927,
    collegeName: 'Kent State Master Science Health Informatics',
    levels: [levelConstant.MASTER],
    additionalParameters: {},
    type: ['everspring'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
  KENT_STATE_MS_GEOGRAPHIC: {
    collegeId: 3928,
    collegeName: 'Kent State Master Science Geographic Information Science',
    levels: [levelConstant.MASTER],
    additionalParameters: {},
    type: ['everspring'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
  KENT_STATE_MS_CRIMINOLOGY: {
    collegeId: 3929,
    collegeName: 'Kent State Master Criminology Criminal Justice',
    levels: [levelConstant.MASTER],
    additionalParameters: {},
    type: ['everspring'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
  KENT_STATE_MPH: {
    collegeId: 3926,
    collegeName: 'Kent State Masters Public Health',
    levels: [levelConstant.DOCTORATE],
    additionalParameters: {},
    type: ['everspring'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
  MARQUETTE_MS_COMPUTING: {
    collegeId: 3930,
    collegeName: 'Marquette University Master Science Computing',
    levels: [levelConstant.MASTER],
    additionalParameters: {},
    type: ['everspring'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
  MARQUETTE_MS_HEALTH: {
    collegeId: 3931,
    collegeName: 'Marquette University Master Health Care Data Analytics',
    levels: [levelConstant.MASTER],
    additionalParameters: {},
    type: ['everspring'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
  TENNESSEE_KNOXVILLE: {
    collegeId: 3938,
    collegeName: 'Master of Science in Supply Chain Management Online',
    levels: [],
    additionalParameters: {},
    type: ['noodle'],
    hasReferanceCode: false,
    defaultDegree: '',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
  NATIONAL_UNIVERSITY: {
    collegeId: 192,
    collegeName: 'National University',
    levels: [],
    additionalParameters: {
      PhoneNumber_EWC: 1,
      PhoneNumber_Mobile: 1,
      PhoneNumber_SMSOptin: 1,
      SourceCode: "CLGRCNRFL",
      LeadBuyerID: 623,
      interfaceid: "leadCaptureNU",
      SID: 17871,
      SupplierID: 365195,
      NUContactMethod: "Lead Vendor",
      CampaignActivity: "CLGRCNRFL",
      DesignatedTeam: "Online Region",
      DesignatedMilitaryTeam: "MIL Online"
    },
    type: ['sparkroom'],
    hasReferanceCode: true,
    defaultDegree: 'UNDECIDED',
    requiredParameters: [],
    googleSheetID: [],
    singleDegree: null,
  },
};

const everSpringCollegeList = [3933, 3932, 3926, 3927, 3928, 3929, 3930, 3931, 3938];

const vaClaimsConstant = {
  CLAIMS_POST_URL:
    'https://leads01.disabilitylawclaims.com/ws/wsleads.nsf/api/data/documents?form=WSLead&computewithform=true',
  SOURCEID: 'F660E258937C893F852588DE0043124F',
  CLIENTID: '686D66920428AEA185257E84006E651F',
  VACLAIMS: 'vaclaims',
  INTEGRATION_VACLAIMS: 'VaClaims Integration',
};

module.exports = {
  integrationConstant,
  collegeConstant,
  everSpringCollegeList,
  vaClaimsConstant,
};
