exports.SAVE_REPLY_STUDENT_MESSAGE = "INSERT INTO recon_messages SET ?"
exports.GET_VETERAN_REPLY_RECEIVED_MESSAGE ="SELECT count(*) as replies_received FROM recon_messages WHERE student_id = ? AND responder = 'COLLEGE'";
exports.GET_VETERAN_INBOX_MESSAGE_COUNT = "SELECT count(message_id) as cinbox FROM recon_messages WHERE student_id = ? AND recipient = 'USER' AND message_state = 'NEW'"; 
exports.GET_COLLEGE_INBOX_MESSAGE_COUNT = "SELECT count(message_id) as cinbox FROM recon_messages WHERE college_id = ? AND recipient = 'COLLEGE' AND message_state = 'NEW'"; 
exports.GET_VETERAN_MESSAGES = "SELECT rm.*,c.college_name,c.college_alias,c.seo_name,cp.college_logo,c.contact_email,sp.profile_image FROM recon_messages as rm LEFT JOIN colleges as c ON c.id=rm.college_id LEFT JOIN college_profiles as cp ON cp.college_id=rm.college_id LEFT JOIN student_profile as sp ON sp.uuid = rm.student_id WHERE message_state != 'DELETED' AND rm.student_id=? ORDER BY rm.date_created DESC";
exports.GET_VETERAN_MESSAGES_TYPE = "SELECT rm.*,c.college_name,c.college_alias,c.seo_name,cp.college_logo,c.contact_email,sp.profile_image FROM recon_messages as rm LEFT JOIN colleges as c ON c.id=rm.college_id LEFT JOIN college_profiles as cp ON cp.college_id=rm.college_id LEFT JOIN student_profile as sp ON sp.uuid = rm.student_id WHERE message_state != 'DELETED' AND rm.student_id=?  ORDER BY rm.date_created DESC";
exports.REPLIES_RECEIVED_FOR_COLLEGE = "SELECT count(*) as replies_received FROM recon_messages WHERE college_id = ? AND responder = 'USER' AND message_state = 'NEW'";
exports.QUERY_CONTACTED_VETERAN = "SELECT count(distinct(student_id)) as pcount FROM `recon_messages` WHERE college_id = ?";
exports.GET_COLLEGE_MESSAGES = "SELECT rm.*,c.college_name,cp.college_logo,ss.email,sp.profile_image,ss.first_name,ss.middle_initial,ss.last_name FROM recon_messages as rm LEFT JOIN colleges as c ON c.id=rm.college_id LEFT JOIN college_profiles as cp ON cp.college_id=rm.college_id LEFT JOIN student_profile as sp ON sp.uuid = rm.student_id LEFT JOIN students as ss ON ss.uuid=rm.student_id WHERE message_state != 'DELETED' AND rm.college_id=? ORDER BY rm.date_created DESC";
exports.GET_COLLEGE_MESSAGES_TYPE = "SELECT rm.*,c.college_name,cp.college_logo,ss.email,sp.profile_image,ss.first_name,ss.middle_initial,ss.last_name FROM recon_messages as rm LEFT JOIN colleges as c ON c.id=rm.college_id LEFT JOIN college_profiles as cp ON cp.college_id=rm.college_id LEFT JOIN student_profile as sp ON sp.uuid = rm.student_id LEFT JOIN students as ss ON ss.uuid=rm.student_id WHERE message_state != 'DELETED' AND rm.college_id=?  ORDER BY rm.date_created DESC";