const searchConstant = {
  SEARCHDATA_SAVE : "INSERT INTO searchdata SET ?",
  GET_ALL_COLLEGE_SEARCH_QUERY:"Select c.id as collegeId,c.contact_email,c.college_type,HTML_UnEncode(college_name)as college_name,college_alias,seo_name,address,city, state, postal_code, phone_number,website,convert(cast(convert(overview using latin1) as binary) using utf8) as overview, college_logo,college_photo,access_level,cp.full_time_vet_counselors,cp.principles_of_excellence,cp.awards_ace_credit,cp.yellow_ribbon,cp.approved_ta_funding,cp.reduced_tuition,cp.public_private,cp.in_state_tuition,cp.out_state_tuition,tc.display_order,0 as isSpecificDegree,c.specific_profile_id,0 as parentCollegeId FROM colleges c LEFT JOIN college_profiles cp on c.id=cp.college_id LEFT JOIN default_colleges as tc on c.id=tc.college_id where c.status='ACTIVE' AND c.access_level!='Pending' AND c.specific_profile_id = '0'",
  GET_ALL_ONLINE_COLLEGE_SEARCH_QUERY:"Select c.id as collegeId,c.contact_email,c.college_type,HTML_UnEncode(college_name)as college_name,college_alias,seo_name,address,city, state, postal_code, phone_number,website,convert(cast(convert(overview using latin1) as binary) using utf8) as overview, college_logo,college_photo,access_level,cp.full_time_vet_counselors,cp.principles_of_excellence,cp.awards_ace_credit,cp.yellow_ribbon,cp.approved_ta_funding,cp.reduced_tuition,cp.public_private,cp.in_state_tuition,cp.out_state_tuition,'0' as display_order,0 as isSpecificDegree,c.specific_profile_id,0 as parentCollegeId FROM colleges c LEFT JOIN college_profiles cp on c.id=cp.college_id where c.status='ACTIVE' AND c.access_level!='Pending' AND c.specific_profile_id = '0'",
  GET_ALL_ONLINE_COLLEGE_SEARCH_QUERY_WITH_SPECIFIC:"Select c.id as collegeId,c.contact_email,c.college_type,HTML_UnEncode(college_name)as college_name,college_alias,seo_name,address,city, state, postal_code, phone_number,website,convert(cast(convert(overview using latin1) as binary) using utf8) as overview, college_logo,college_photo,access_level,cp.full_time_vet_counselors,cp.principles_of_excellence,cp.awards_ace_credit,cp.yellow_ribbon,cp.approved_ta_funding,cp.reduced_tuition,'0' as display_order,0 as isSpecificDegree,c.specific_profile_id,0 as parentCollegeId FROM colleges c LEFT JOIN college_profiles cp on c.id=cp.college_id where c.status='ACTIVE' AND c.access_level!='Pending' ",
  GET_ALL_COLLEGE_SEARCH_DISPLAY_QUERY:"Select c.id as collegeId,c.contact_email,c.college_type,HTML_UnEncode(college_name)as college_name,college_alias,seo_name,address,city, state, postal_code, phone_number,phone_required,website,convert(cast(convert(overview using latin1) as binary) using utf8) as overview, college_logo,college_photo,access_level,cp.full_time_vet_counselors,cp.principles_of_excellence,cp.awards_ace_credit,cp.yellow_ribbon,cp.approved_ta_funding,cp.reduced_tuition,cp.public_private,cp.in_state_tuition,cp.out_state_tuition,0 as isSpecificDegree,c.specific_profile_id,0 as parentCollegeId FROM colleges c LEFT JOIN college_profiles cp on c.id=cp.college_id LEFT JOIN default_colleges as tc on c.id=tc.college_id where c.status='ACTIVE' AND c.access_level!='Pending' AND c.specific_profile_id = '0'",
  EducationalLevel:[3,5,7,17],
  AppEducationalLevel:['3','5','7','17'],
  BOLD_POST_URL: "https://prodbe.bold.org/api/v1/affiliate/register?key=collegerecon&subId1=",
 };
 //EducationLevel: 3 - Associate, 5 - Bachelors, 7 - Masters, 17 - Doctorate
 module.exports=searchConstant; 